---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: wimpysworld/nothing-but-nix@v10
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            accept-flake-config = true
      - run: nix flake check
      - run: nix run nixpkgs#nixfmt **/*.nix

      # check generate-parsers
      - run: mv generated.nix generated.nix.old
      - run: nix develop --command "generate-parsers"
      - run: diff generated.nix generated.nix.old

      - run: nix build .#nvim-treesitter.withAllGrammars
      # Ensure bundle is injected into source code
      - run: grep -R "/nix/store" result/lua
      # Ensure parsers & queries are linked to rtp
      - run: |-
          test -f result/parser/http.so
          test -d result/queries/http
